name: Build C++ Exe

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Compile C++ Code
      shell: cmd
      run: |
        g++ main.cpp -o macro.exe -lwininet -static-libgcc -static-libstdc++

    - name: Upload Exe Artifact
      uses: actions/upload-artifact@v3
      with:
        name: MacroTool-Exe
        path: macro.exe
